WorkPortal/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    # path('search/', views.search, name='search'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('createJobOffer/', views.create_job_offer, name='job_create'),
    path('createResponseForm/<int:job_offer_id>', views.create_response_form, name="create_response_form"),
    path('details/<int:job_id>/', views.job_detail, name='job_detail'),
    path('respond/<int:job_id>/', views.job_response_form, name='job_response'),
    path('edit/<int:job_id>/', views.edit_job_offer, name='edit_job_offer'),
    path('jobOffers/', views.job_offer_list, name='job_offer_list'),
    path('delete/<int:job_id>/', views.delete_job_offer, name='delete_job_offer'),
    path('manage/', views.manage_job_offers, name='manage_job_offers'),
    path('captcha/', include('captcha.urls')),
]

sem6_django_www_projekt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("WorkPortal.urls"))
]

WorkPortal/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class JobOffer(models.Model):
    CATEGORIES = [
        ("ADB", "Office administration"),
        ("ECO", "E-commerce"),
        ("FWF", "Franchising / Own company"),
        ("HRU", "Hostess, flyer distribution"),
        ("KIE", "Driver"),
        ("MIS", "Installation and service"),
        ("PZG", "Work abroad"),
        ("RIO", "Agriculture and horticulture"),
        ("ZDR", "Health"),
        ("KAK", "Management"),
        ("BIR", "Research and development"),
        ("EDU", "Education"),
        ("FRK", "Hairdressing, beauty treatments"),
        ("HOT", "Hotel industry"),
        ("LZS", "Logistics, purchasing, forwarding"),
        ("OCC", "Customer service and call center"),
        ("PRM", "Warehouse work"),
        ("SPR", "Cleaning"),
        ("POP", "Other job offers"),
        ("BUD", "Construction / renovations"),
        ("ENG", "Power industry"),
        ("GAS", "Catering"),
        ("INZ", "Engineering"),
        ("MPR", "Marketing and PR"),
        ("OCH", "Security"),
        ("PSK", "Shop assistant"),
        ("SPR", "Sales"),
        ("PDS", "Additional / seasonal work"),
        ("DKM", "Courier, city delivery"),
        ("FIK", "Finance / accounting"),
        ("HRR", "HR"),
        ("ITT", "IT / telecommunications"),
        ("MIL", "Mechanics and car painting"),
        ("OPI", "Care"),
        ("PRS", "Internships"),
        ("PRO", "Production"),
        ("WET", "Shelf-stocking and product presentation")
    ]

    CONTRACT_TYPES = [
        ("UOP", "Employment contract"),
        ("UOD", "Contract of mandate"),
        ("UZL", "Contract for specific task"),
        ("B2B", "B2B contract"),
        ("UNZ", "Substitution contract"),
        ("UAG", "Agency contract"),
        ("UPT", "Temporary employment contract"),
        ("USP", "Apprenticeship / internship contract")
    ]

    EXPECTED_EDUCATION = [
        ("POD", "Basic education"),
        ("GIM", "Secondary education"),
        ("WZZ", "Basic vocational education"),
        ("WZB", "Basic vocational education in a specific trade"),
        ("WSB", "Vocational education in a specific trade"),
        ("WSR", "Secondary education"),
        ("WWY", "Higher education")
    ]

    OPERATING_MODE = [
        ("PST", "Stationary work"),
        ("PZD", "Remote work"),
        ("PHY", "Hybrid work"),
        ("PMO", "Mobile work")
    ]

    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=3, choices=CATEGORIES)
    title = models.CharField(max_length=256)
    expiration_date = models.DateTimeField(null=True, blank=True)
    localization = models.CharField(max_length=256, null=True, blank=True)
    description = models.CharField(max_length=4096)
    rate = models.IntegerField(null=True, blank=True)
    contract_type = models.CharField(max_length=3, choices=CONTRACT_TYPES)
    expected_education = models.CharField(max_length=3, choices=EXPECTED_EDUCATION, null=True, blank=True)
    expected_age = models.CharField(max_length=16, null=True, blank=True)
    required_experience = models.IntegerField(null=True, blank=True)
    operating_mode = models.CharField(max_length=3, choices=OPERATING_MODE, null=True, blank=True)
    shift_work = models.BooleanField()
    weekend_work = models.BooleanField()
    flexible_working_time = models.BooleanField()


class JobResponse(models.Model):
    job_offer_id = models.ForeignKey(JobOffer, on_delete=models.CASCADE)
    link = models.CharField(max_length=512, null=True, blank=True)
    email = models.BooleanField()
    cv = models.BooleanField()
    letter_of_motivation = models.BooleanField()
    expected_wage = models.BooleanField()


class ResponsesCounter(models.Model):
    job_offer_id = models.ForeignKey(JobOffer, on_delete=models.CASCADE)
    count = models.IntegerField()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<header class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light container">
        <a class="navbar-brand" href="{% url 'home' %}">Work Portal</a>
        <a class="nav-link" href="{% url 'job_offer_list' %}">Offers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'job_create' %}">Create job offer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'manage_job_offers' %}">Hello {{ user.username }}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}?next={{ request.path }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

templates/createJobOffer.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h2>Create Job offer</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="hidden" name="user_id" value="{{ request.user.id }}">
            <button type="submit" class="btn btn-primary">Create Job Offer</button>
        </form>
    </div>
{% endblock %}

templates/createResponseForm.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h2>Create Job offer response form</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Create Job Offer Response Form</button>
        </form>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="container">
    <p class="fs-1 text-center">Search for offers</p>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <form method="GET" action="{% url 'job_offer_list' %}">
          <div class="input-group input-group-lg mb-3">
            <input type="text" class="form-control" placeholder="Search" name="search">
            <div class="input-group-append">
              <button class="btn btn-lg btn-outline-secondary" type="submit">Search</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row justify-content-center">
    <p class="fs-1 text-center">Search by Categories</p>
      <div class="col-lg-12 col-md-12">
        <div class="btn-group" role="group" style="display: flex; flex-wrap: wrap;">
          {% for category in categories %}
            <a href="{% url 'job_offer_list' %}?category={{ category.0 }}" class="btn btn-primary btn-lg {% if category_filter == category.0 %}active{% endif %}" style="margin: 5px;">
              {{ category.1 }}
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/jobOfferDetails.html
{% extends 'base.html' %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">{{ job.title }}</h1>
                </div>

                <div class="card-body">
                    {% if show_button %}
                        <div class="row justify-content-center py-3">
                            <a href="{% url 'edit_job_offer' job.id %}"
                               class="btn btn-primary col-sm-5 mx-3">Edit</a>
                            <a href="{% url 'delete_job_offer' job.id %}"
                               class="btn btn-danger col-sm-5 mx-3">Delete</a>
                        </div>
                        <div class="row justify-content-center py-3 mx-3">
                            <label for="response_count" class="form-text">Responses:</label>
                            <p id="response_count"
                               class="form-label">{{ count }}</p>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Category:</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.get_category_display }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Expiration date</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.expiration_date }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Localization:</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.localization }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Description:</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.description }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Rate:</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.rate }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Contract type</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.get_contract_type_display }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Expected education</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.get_expected_education_display }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Expected age</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.expected_age }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Required experience</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.required_experience }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Operating mode</div>
                        <div class="col-sm-5 form-label mx-3">{{ job.get_operating_mode_display }}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Shift work</div>
                        <div class="col-sm-5 form-label mx-3">{% if job.shift_work %}Yes{% else %}No{% endif %}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Weekend work</div>
                        <div class="col-sm-5 form-label mx-3">{% if job.weekend_work %}Yes{% else %}No{% endif %}</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5 form-label mx-3 fw-bold">Flexible working</div>
                        <div class="col-sm-5 form-label mx-3">{% if job.flexible_working_time %}Yes{% else %}
                            No{% endif %}</div>
                    </div>
                    <div class="d-flex flex-column">
                        <a href="{% url 'job_response' job.id %}"
                           class="btn btn-primary">Respond offer</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/jobOfferEdit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-lg-6">
            <h1 class="text-center mb-4">Job Offer Details</h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="row">
                    <input type="submit" value="Save Changes" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/jobOfferResponse.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-lg-6">
            <h1 class="text-center mb-4">Job Offer Response</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="row">
                    <input type="submit" value="Save Changes" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/jobOffersList.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Job Offers</h1>

    <!-- Add a search form to filter the job offers -->
    <form method="GET" action="{% url 'job_offer_list' %}">
        <div class="form-row">
            <div class="form-group col-md-12">
                <input type="text" class="form-control" placeholder="Search job offers" name="search">
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-sm-3 form-group">
                <label for="category">Category:</label>
                <select name="category" id="category" class="form-control">
                    <option value="">-- All Categories --</option>
                    {% for category, label in job_offer_categories %}
                        <option value="{{ category }}"
                                {% if category == request.GET.category %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-3 form-group">
                <label for="contract_type">Contract type:</label>
                <select name="contract_type" id="contract_type" class="form-control">
                    <option value="">-- All contract types --</option>
                    {% for contract_type, label in job_offer_contract_types %}
                        <option value="{{ contract_type }}"
                                {% if contract_type == request.GET.contract_type %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-3 form-group">
                <label for="expected_education">Expected education:</label>
                <select name="expected_education" id="expected_education" class="form-control">
                    <option value="">-- All expected education types --</option>
                    {% for expected_education, label in job_offer_expected_education %}
                        <option value="{{ expected_education }}"
                                {% if expected_education == request.GET.expected_education %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-3 form-group">
                <label for="operating_mode">Operating mode:</label>
                <select name="operating_mode" id="operating_mode" class="form-control">
                    <option value="">-- All operating modes --</option>
                    {% for operating_mode, label in job_offer_operating_mode %}
                        <option value="{{ operating_mode }}"
                                {% if operating_mode == request.GET.operating_mode %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-row">
        <div class="form-group col-md-12 text-center mt-3">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </div>
    </form>

    <table class="table">
        <thead>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Expiration Date</th>
            <th>Localization</th>
            <th>Details</th>
        </tr>
        </thead>
        <tbody>
        {% for job_offer in job_offers %}
            <tr>
                <td>{{ job_offer.title }}</td>
                <td>{{ job_offer.get_category_display }}</td>
                <td>{{ job_offer.expiration_date }}</td>
                <td>{{ job_offer.localization }}</td>
                <td>
                    <a href="{% url 'job_detail' job_offer.id %}" class="btn btn-primary">Details</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">No job offers found.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Log in</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="mb-3">
                                    {{ field.label_tag}}
                                    {{ field|add_class:'form-control' }}
                                    <span class="form-label"></span>
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <button class="btn btn-primary mt-3" type="submit">Log in</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/manage.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-lg-12">
            <h1 class="text-center py-2">Manage your job offers</h1>
            {% for offer in job_offers %}
                <div class="py-2">
                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'job_detail' offer.id %}"><h3>{{ offer.title }}</h3></a>
                            <label for="response_count" class="form-text">Responses:</label>
                            <p id="response_count"
                               class="form-label">{{ job_responses|get_response_counter:offer.id }}</p>
                        </div>
                        <div class="card-body">
                            <div class="row col-12">
                                <div class="col-4">
                                    <label for="contract_type" class="form-text">Location:</label>
                                    <p id="contract_type" class="form-label">{{ offer.localization }}</p>
                                    <label for="operating_mode" class="form-text">Expiration date:</label>
                                    <p id="operating_mode" class="form-label">{{ offer.expiration_date }}</p>
                                </div>
                                <div class="col-3">
                                    <label for="contract_type" class="form-text">Category:</label>
                                    <p id="contract_type" class="form-label">{{ offer.get_category_display }}</p>
                                    <label for="operating_mode" class="form-text">Required experience:</label>
                                    <p id="operating_mode" class="form-label">{{ offer.required_experience }} years</p>
                                </div>
                                <div class="col-3">
                                    <label for="contract_type" class="form-text">Contract type:</label>
                                    <p id="contract_type" class="form-label">{{ offer.get_contract_type_display }}</p>
                                    <label for="operating_mode" class="form-text">Operating mode:</label>
                                    <p id="operating_mode" class="form-label">{{ offer.get_operating_mode_display }}</p>
                                </div>
                                <div class="col-2">
                                    <div class="d-flex flex-column">
                                        <a href="{% url 'edit_job_offer' offer.id %}"
                                           class="btn btn-primary mb-2">Edit</a>
                                    </div>
                                    <div class="d-flex flex-column">
                                        <a href="{% url 'delete_job_offer' offer.id %}"
                                           class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}


            {#            <div class="row">#}
            {#                {% if show_button %}#}
            {#                    <a href="{% url 'edit_job_offer' job.id %}" class="btn btn-primary">Edit</a>#}
            {#                {% endif %}#}
            {#            </div>#}
        </div>
    </div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="card">
    <div class="card-header">
      <h2>Register</h2>
    </div>
    <div class="card-body">
      {% crispy form %}
    </div>
  </div>
{% endblock %}